# Generated by Django 2.2.5 on 2019-11-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10)),
                ('imagem', models.ImageField(upload_to='imagens_analise/')),
                ('resultado', models.CharField(max_length=3)),
            ],
        ),
    ]
