# Generated by Django 2.2.5 on 2019-11-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_ia', '0002_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='resultado',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
