# Generated by Django 2.2.5 on 2019-11-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_ia', '0006_auto_20191123_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='analise',
            name='imagem_analisada',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
